"""add 1-to-many relationship

Revision ID: 390484007ba6
Revises: 
Create Date: 2022-09-23 23:16:59.364768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390484007ba6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'store_id')
    # ### end Alembic commands ###
